### ISSUE TITLE
Get a LICENSE

### ISSUE THREAD

**Issue by jasonwynn10** [ArceusMatt/ALPHAHack#4]
1. Without the right license, anyone can fork your work and make it their own.
2. copyright doesn't apply without a proper license
3. In case you don't understand this already, people don't like to listen when they are told what to do. Without a license, this work is now without a legitimate copyright and anyone can claim a copyright on it.
Fair warning...

**Comment by ArceusMatt** [comment]
Was going to but never did, thanks for warning in advanced.

**Comment by ArceusMatt** [comment]
Added also... as original author of AlphaHackPE i don't care if you fork and edit it's free to use as of now.. the old script had things i didnt want skids messing up and stuff i was also new to github.
